# Settings
font_family CaskaydiaCove Nerd Font
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 0
shell_integration no-cursor
cursor_blink_interval 0.5 ease-in-out
cursor_stop_blinking_after 15.0
tab_bar_style powerline
tab_bar_min_tabs 1
tab_bar_show_new_tab_button yes
wayland_enable_ime yes

# Themes
background #212324
foreground #b9b9b9
cursor #bbbbbb
selection_background #9C8C6F
color0 #B9B9B9
color8 #000000
color1 #e8331c
color9 #df5a4f
color2 #68c156
color10 #76b768
color3 #f1d32b
color11 #eed64a
color4 #1c98e8
color12 #387bd2
color5 #8e69c8
color13 #957bbd
color6 #1c98e8
color14 #3d96e2
color7 #b9b9b9
color15 #b9b9b9
selection_foreground #212324
active_tab_background #35434a
active_tab_foreground #dce7eb
inactive_tab_background #292c2d
inactive_tab_foreground #777b7c
active_border_color #e8331c
inactive_border_color #444444
wayland_titlebar_color #212324
