# Settings
font_family CaskaydiaCove Nerd Font
cursor_shape beam
cursor_beam_thickness 1
cursor_trail 1
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 0
shell_integration no-cursor
cursor_blink_interval 0.5 ease-in-out
cursor_stop_blinking_after 15.0
tab_bar_style powerline
tab_bar_min_tabs 1
active_tab_font_style bold
tab_bar_show_new_tab_button yes
tab_bar_edge top
mouse_map left click ungrabbed  
mouse_map shift+left click ungrabbed mouse_handle_click selection link prompt 

# Apps
open_url_with firefox

# Themes (Breeze Dark)
background #141618
foreground #fcfcfc
cursor #fcfcfc
selection_background #185a81
selection_foreground #ffffff

# 标准 8 色
color0 #141618
color1 #da4453
color2 #27ae60
color3 #f67400
color4 #1a78ae
color5 #9B59B6
color6 #1a78ae
color7 #a1a9b1

# 亮色 8 色
color8  #5d6570
color9  #da4453
color10 #27ae60
color11 #f67400
color12 #1a78ae
color13 #9B59B6
color14 #1a78ae
color15 #fcfcfc

# 标签页
active_tab_background #35434a
active_tab_foreground #dce7eb
inactive_tab_background #292c2d
inactive_tab_foreground #777b7c

# 窗口边框
active_border_color #1a78ae
inactive_border_color #292c30
wayland_titlebar_color #202326
